apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    app: promtail
